/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProductController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Product;

/**
 * **ProductView.java**
 * Esta classe representa a tela para Adicionar (Create) ou Editar (Update) um produto.
 */
public class ProductView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductView.class.getName());
    private final ProductController productController = new ProductController();
    private Product currentProduct;
    
    /**
     * Construtor para Novo Produto (CREATE).
     */
    public ProductView() {
        initComponents();
        setTitle("Novo Produto");
        aplicarEstilo();
    }
    
    /**
     * Construtor para Editar Produto (UPDATE).
     */
    public ProductView(Product productToEdit) {
        initComponents();

        this.currentProduct = productToEdit;
       
        setTitle("Editar Produto: " + productToEdit.getName());

        ftfNome.setText(productToEdit.getName());
        ftfValor.setText(String.valueOf(productToEdit.getPrice()));
        ftfEstoque.setText(String.valueOf(productToEdit.getStockQuantity()));
        ftfPonto.setText(String.valueOf(productToEdit.getPointCost()));
        cmbTipo.setSelectedItem(productToEdit.getType()); 
        
        aplicarEstilo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        ftfNome = new javax.swing.JFormattedTextField();
        lblValor = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        lblPonto = new javax.swing.JLabel();
        ftfValor = new javax.swing.JFormattedTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        ftfEstoque = new javax.swing.JFormattedTextField();
        ftfPonto = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNome.setText("Nome");

        ftfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfNomeActionPerformed(evt);
            }
        });

        lblValor.setText("Valor");

        lblTipo.setText("Tipo");

        lblEstoque.setText("Quantidade em estoque");

        lblPonto.setText("Pontos");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Pão salgado", "Pão doce", "Salgado", "Doce/confeitaria", "Bebida", "Frios/laticínios", "Mercearia" }));
        cmbTipo.setToolTipText("");
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(ftfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPonto)
                            .addComponent(lblValor)
                            .addComponent(lblTipo)
                            .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftfPonto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftfEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEstoque, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTipo)
                .addGap(9, 9, 9)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblPonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ftfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfNomeActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        try{
            String tipoSelecionado = (String) cmbTipo.getSelectedItem();

            Product product = new Product(ftfNome.getText(), Double.parseDouble(ftfValor.getText()), tipoSelecionado, Integer.parseInt(ftfEstoque.getText()), Integer.parseInt(ftfPonto.getText()));
            
            if(this.currentProduct == null){
                Integer id = productController.saveProduct(product);       
                this.currentProduct = productController.findById(id); 
            } else {
                productController.updateProduct(product, this.currentProduct.getId());
            }
               
            JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        
        } catch (NumberFormatException e) {
            
            JOptionPane.showMessageDialog(this, "Erro: Certifique-se de que Preço, Estoque e Pontos são números válidos.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);

        } catch (IllegalArgumentException e) {
      
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação", JOptionPane.WARNING_MESSAGE);

        } catch (RuntimeException e) {

            JOptionPane.showMessageDialog(this, "Erro ao salvar no banco de dados: " + e.getMessage(), "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();  
    }//GEN-LAST:event_btnVoltarActionPerformed

    // --- Estilização e Aparência ---
    private void aplicarEstilo() {

        jPanel1.setBackground(new Color(250, 245, 235)); 

        lblNome.setForeground(new Color(90, 70, 50));
        lblValor.setForeground(new Color(90, 70, 50));
        lblTipo.setForeground(new Color(90, 70, 50));
        lblEstoque.setForeground(new Color(90, 70, 50));
        lblPonto.setForeground(new Color(90, 70, 50));

        ftfNome.setBackground(new Color(255, 252, 245));
        ftfNome.setBorder(BorderFactory.createLineBorder(new Color(200, 180, 150)));

        ftfValor.setBackground(new Color(255, 252, 245));
        ftfValor.setBorder(BorderFactory.createLineBorder(new Color(200, 180, 150)));

        ftfEstoque.setBackground(new Color(255, 252, 245));
        ftfEstoque.setBorder(BorderFactory.createLineBorder(new Color(200, 180, 150)));

        ftfPonto.setBackground(new Color(255, 252, 245));
        ftfPonto.setBorder(BorderFactory.createLineBorder(new Color(200, 180, 150)));

        cmbTipo.setBackground(new Color(255, 252, 245));
        cmbTipo.setBorder(BorderFactory.createLineBorder(new Color(200, 180, 150)));

        estilizarBotao(btnSalvar);
        estilizarBotao(btnVoltar);
    }

    private void estilizarBotao(JButton botao) {
        Color corNormal = new Color(180, 150, 120);
        Color corHover = new Color(160, 130, 100);

        botao.setBackground(corNormal);
        botao.setForeground(Color.WHITE);
        botao.setFont(new Font("Segoe UI", Font.BOLD, 13));
        botao.setBorderPainted(false);
        botao.setFocusPainted(false);
        botao.setCursor(new Cursor(Cursor.HAND_CURSOR));

        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                botao.setBackground(corHover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                botao.setBackground(corNormal);
            }
        });
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JFormattedTextField ftfEstoque;
    private javax.swing.JFormattedTextField ftfNome;
    private javax.swing.JFormattedTextField ftfPonto;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPonto;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
